import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { DiffDialog, type DiffDialogProps } from './diff-dialog';

// Mock the diff utility to avoid needing the full 'diff' library in tests
vi.mock('@/features/prompts/utils/diff', () => ({
  calculateDiff: vi.fn((_old: string, _new: string) => [
    { content: 'original line', type: 'removed' as const, oldLineNumber: 1 },
    { content: 'structured line', type: 'added' as const, newLineNumber: 1 },
  ]),
}));

const defaultProps: DiffDialogProps = {
  open: true,
  onOpenChange: vi.fn(),
  originalText: 'original brainstorm text',
  structuredText: '# Structured Prompt\n\nHello world',
  model: 'claude-sonnet-4-20250514',
  onAccept: vi.fn(),
  onReject: vi.fn(),
};

describe('DiffDialog', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders dialog with title and model info', () => {
    render(<DiffDialog {...defaultProps} />);

    expect(screen.getByText('AI Structured Result')).toBeInTheDocument();
    expect(
      screen.getByText(/Generated by claude-sonnet-4-20250514/),
    ).toBeInTheDocument();
  });

  it('renders diff content with original and structured lines', () => {
    render(<DiffDialog {...defaultProps} />);

    expect(screen.getByText('original line')).toBeInTheDocument();
    expect(screen.getByText('structured line')).toBeInTheDocument();
  });

  it('calls onAccept with structured text when Accept is clicked', () => {
    render(<DiffDialog {...defaultProps} />);

    fireEvent.click(screen.getByText('Accept'));

    expect(defaultProps.onAccept).toHaveBeenCalledWith(
      '# Structured Prompt\n\nHello world',
    );
    expect(defaultProps.onOpenChange).toHaveBeenCalledWith(false);
  });

  it('calls onReject when Reject is clicked', () => {
    render(<DiffDialog {...defaultProps} />);

    fireEvent.click(screen.getByText('Reject'));

    expect(defaultProps.onReject).toHaveBeenCalledTimes(1);
    expect(defaultProps.onOpenChange).toHaveBeenCalledWith(false);
  });

  it('switches to edit mode when Edit is clicked', () => {
    render(<DiffDialog {...defaultProps} />);

    // Initially in preview mode
    expect(screen.getByText('Edit')).toBeInTheDocument();

    fireEvent.click(screen.getByText('Edit'));

    // Now in edit mode — should show a textarea and Preview button
    expect(screen.getByText('Preview')).toBeInTheDocument();
    expect(screen.getByRole('textbox')).toBeInTheDocument();
  });

  it('accepts edited content when in edit mode', () => {
    render(<DiffDialog {...defaultProps} />);

    // Enter edit mode
    fireEvent.click(screen.getByText('Edit'));

    // Modify content
    const textarea = screen.getByRole('textbox');
    fireEvent.change(textarea, { target: { value: 'manually edited' } });

    // Accept
    fireEvent.click(screen.getByText('Accept'));

    expect(defaultProps.onAccept).toHaveBeenCalledWith('manually edited');
  });

  it('shows generic description when no model is provided', () => {
    render(<DiffDialog {...defaultProps} model={undefined} />);

    expect(
      screen.getByText(/Review the AI-structured output/),
    ).toBeInTheDocument();
  });

  it('renders legend indicators', () => {
    render(<DiffDialog {...defaultProps} />);

    expect(screen.getByText('Original')).toBeInTheDocument();
    expect(screen.getByText('Structured')).toBeInTheDocument();
  });
});
