'use client';

// ---------------------------------------------------------------------------
// DiffDialog — preview AI-structured result before accepting/rejecting
// ---------------------------------------------------------------------------

import { useMemo, useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { ScrollArea } from '@/components/ui/scroll-area';
import { calculateDiff } from '@/features/prompts/utils/diff';
import { cn } from '@/lib/utils';
import { Check, X, Pencil, Eye } from 'lucide-react';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface DiffDialogProps {
  /** Whether the dialog is open. */
  open: boolean;
  /** Callback to control open state. */
  onOpenChange: (open: boolean) => void;
  /** The original brainstorm text. */
  originalText: string;
  /** The AI-structured result text. */
  structuredText: string;
  /** The model that produced the result (for display). */
  model?: string;
  /** Callback when user accepts the structured result. */
  onAccept: (content: string) => void;
  /** Callback when user rejects (keeps original). */
  onReject: () => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function DiffDialog({
  open,
  onOpenChange,
  originalText,
  structuredText,
  model,
  onAccept,
  onReject,
}: DiffDialogProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState(structuredText);

  // Reset editing state when dialog opens with new content
  const [prevStructured, setPrevStructured] = useState(structuredText);
  if (structuredText !== prevStructured) {
    setPrevStructured(structuredText);
    setEditedContent(structuredText);
    setIsEditing(false);
  }

  const diff = useMemo(
    () => calculateDiff(originalText, isEditing ? editedContent : structuredText),
    [originalText, structuredText, editedContent, isEditing],
  );

  const handleAccept = () => {
    onAccept(isEditing ? editedContent : structuredText);
    onOpenChange(false);
  };

  const handleReject = () => {
    onReject();
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl h-[80vh] flex flex-col p-0 gap-0 border-border bg-sidebar overflow-hidden">
        <DialogHeader className="p-4 md:p-6 border-b border-sidebar-border shrink-0">
          <DialogTitle className="text-lg md:text-xl font-bold text-foreground">
            AI Structured Result
          </DialogTitle>
          <DialogDescription className="text-xs md:text-sm text-muted-foreground">
            {model ? `Generated by ${model}` : 'Review the AI-structured output'}
            {' — '}compare your brainstorm notes with the structured result.
          </DialogDescription>
        </DialogHeader>

        {/* Content area */}
        <div className="flex-1 overflow-hidden bg-background">
          {isEditing ? (
            <div className="h-full p-4">
              <Textarea
                value={editedContent}
                onChange={(e) => setEditedContent(e.target.value)}
                className="h-full min-h-0 font-mono text-sm resize-none"
                autoFocus
              />
            </div>
          ) : (
            <ScrollArea className="h-full">
              <div className="font-mono text-[11px] md:text-xs leading-relaxed p-0 min-w-full">
                {diff.map((line, index) => (
                  <div
                    key={index}
                    className={cn(
                      'flex min-w-full whitespace-pre group',
                      line.type === 'added' && 'bg-green-500/10 text-green-500',
                      line.type === 'removed' && 'bg-red-500/10 text-red-500',
                      line.type === 'unchanged' && 'text-muted-foreground/80 hover:bg-muted/30',
                    )}
                  >
                    {/* Gutter */}
                    <div className="flex-none flex select-none border-r border-border/30 bg-muted/20">
                      <div className="w-8 md:w-10 text-center py-0.5 text-[10px] text-muted-foreground/50 border-r border-border/10">
                        {line.oldLineNumber || ''}
                      </div>
                      <div className="w-8 md:w-10 text-center py-0.5 text-[10px] text-muted-foreground/50 border-r border-border/10">
                        {line.newLineNumber || ''}
                      </div>
                      <div
                        className={cn(
                          'w-6 md:w-8 text-center py-0.5 font-bold',
                          line.type === 'added' && 'text-green-500',
                          line.type === 'removed' && 'text-red-500',
                        )}
                      >
                        {line.type === 'added' ? '+' : line.type === 'removed' ? '-' : ' '}
                      </div>
                    </div>

                    {/* Content */}
                    <div className="flex-1 px-3 py-0.5 break-all md:break-words">
                      {line.content || ' '}
                    </div>
                  </div>
                ))}
              </div>
            </ScrollArea>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-sidebar-border bg-sidebar shrink-0">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            {/* Legend */}
            <div className="flex gap-4 text-[10px] md:text-xs text-muted-foreground">
              <span className="flex items-center gap-1.5">
                <span className="h-2 w-2 rounded-full bg-red-500/50" /> Original
              </span>
              <span className="flex items-center gap-1.5">
                <span className="h-2 w-2 rounded-full bg-green-500/50" /> Structured
              </span>
            </div>

            {/* Actions */}
            <DialogFooter className="flex-row gap-2 sm:gap-2">
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={() => setIsEditing(!isEditing)}
                className="gap-1.5"
              >
                {isEditing ? (
                  <>
                    <Eye className="size-3.5" />
                    <span className="text-xs">Preview</span>
                  </>
                ) : (
                  <>
                    <Pencil className="size-3.5" />
                    <span className="text-xs">Edit</span>
                  </>
                )}
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleReject}
                className="gap-1.5"
              >
                <X className="size-3.5" />
                <span className="text-xs">Reject</span>
              </Button>
              <Button
                type="button"
                size="sm"
                onClick={handleAccept}
                className="gap-1.5"
              >
                <Check className="size-3.5" />
                <span className="text-xs">Accept</span>
              </Button>
            </DialogFooter>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
